name: flutter_application_1
description: "Audio waveform visualizer with MP4 export."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shadcn_flutter: ^0.0.52
  shared_preferences: ^2.5.4
  just_audio: ^0.10.5
  flutter_riverpod: ^3.3.1
  flutter_soloud: ^4.0.0
  audio_decoder: ^0.1.0
  fftea: ^1.5.0+1
  ffmpeg_kit_flutter_new: ^4.1.0
  pool: ^1.5.1
  file_picker: ^8.0.0
  path_provider: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/

  uses-material-design: true
plugins:
  riverpod_lint: 3.1.3
