const int kFftSize = 4096;
const double kMinFreq = 20.0;
const double kMaxFreq = 16000.0;
const int kExportWidth = 1280;
const int kExportHeight = 720;
const int kExportFps = 30;
const double kExportDt = 1.0 / kExportFps;
const int kPoolSize = 4;
const double kHopRatio = 0.5;
